### ISSUE TITLE
Display basic corpus metrics on front page

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-frontend#5]
Maybe we can display basic corpus metrics on the front page (where you can select the corpus).

Things like this (numbers are arbitrary):

- [x] number of plays: 465
- [x] &#60;persName&#62;: 998
- [ ] &#60;text&#62;: 2,383,325 tokens (see #11)
- [ ] &#60;sp&#62;: 2,027,528 tokens
- [ ] &#60;stage&#62; directions: 7,500 featuring 538,170 tokens
- [ ] Last database update: 10 Nov 2017, 08:15 p.m. (see #12)

**Comment by cmil** [comment]
@lehkost: should these metrics be summed up for all corpora or listed separately for each?

**Comment by lehkost** [comment]
i would list them separately for each corpus. the "last database update" could probably be an overall value, if we always synchronise both corpora at the same time. if not, we could have the "update date" for each corpus individually as well.

**Comment by cmil** [comment]
Basic metrics are available as of v0.3.0. For more detailed information I opened the issues #11 and #12. Please follow up there.
